# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Sean Feeney
copyright: 2001-2025 All Rights Reserved.
title: Anomaly Response Network
description: The Anomaly Response Network is dedicated to the objective study of all forms of unusual phenomena.
long_description: The Anomaly Response Network is dedicated to the objective study of all forms of unusual phenomena including crop circles, ghosts, UFOs, bigfoot, abductions and mutilations.
keywords: ufo, ufos, ghost, ghosts, ghosthunt, hunter, hunt, bigfoot, bigfeet, crop, circle, circles, abduction, abductions, mutilation, mutilations, arizona, phoenix, unidentified, flying, objects, uap, unusual, anomaly, strange, anomalous, unexplained, mystery, mysterious, reports, report, sightings, sighting, phenomena, phenomenon, skeptic, skeptical, critical, saucer, cover, up, cover-up, conspiracy, fumes, light, lights, smell, smells, event, events, cattle, county, maricopa, counties, wpafb, wright, patterson, luke, air, space, force, base, bases, aatip, aerospace, threat, nkypyg, northern, kentucky, paranormal, youth, group, plane, aerial, home page, homepage
lang: en-US
google_analytics: UA-936138-3

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://test.anomalyresponse.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title:output_ext

logo: /assets/img/thumb_ep2.jpg

twitter_username: anomalyresponse
facebook_username: anomalyresponse
github_username: SeanFromIT

twitter:
  username: anomalyresponse
  card: summary

social:
  name: Anomaly Response Network
  links:
    - https://twitter.com/anomalyresponse
    - https://www.facebook.com/anomalyresponse
    - https://github.com/SeanFromIT

# Custom Data Types
collections:
  links:
    output: true

# Build settings
#incremental: true
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

feed:
  collections:
    - links

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
